version: '2'

services:
  # Baseline influx db
  influxdb:
    build: 
      context: ./influxdb
      dockerfile: Dockerfile
    image: mas_influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"  
      - "2003:2003"  
    env_file:
      - 'env.influxdb'
    volumes:
      - /mnt/docker/influx:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - /mnt/docker/grafana:/var/lib/grafana

  elk:
    image: sebp/elk:latest
    container_name: elk
    ports:
      - "9200:9200"
      - "5601:5601"
      - "5044:5044"
    volumes:
      - /mnt/docker/elk:/var/lib/elasticsearch

  telegrafhost:
    image: 'mabsimms/telegraf-host:latest'
    environment:
      - INFLUX_SERVER=influxdb
      - INFLUX_PORT=8086
      - INFLUX_DB=host
      - affinity:container!=*telegrafhost* 
    privileged: true
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  default:
    external:
      name: build2017-demo-network
