version: '2'

services:
  # Baseline influx db
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"  
    env_file:
      - 'env.influxdb'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb

  elk:
    image: sebp/elk:latest
    container_name: elk
    ports:
      - "9200:9200"
      - "5601:5601"
      - "5044:5044"
    volumes:
      - /mnt/docker/elk:/var/lib/elasticsearch
