version: '3'

services:
  # Baseline influx db
  influxdb:
    image: mabsimms/mas_influxdb:latest
    ports:
      - "8086:8086"
      - "2003:2003"
    volumes:
      - influx-data:/var/lib/influxdb
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=1
    deploy:
      placement:
        constraints: [node.labels.role == monitoring]

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    deploy:
      placement:
        constraints: [node.labels.role == monitoring]

#  elk:
#    image: sebp/elk:latest
#    ports:
#      - "5601:5601"
#    volumes:
#      - /mnt/docker/elk:/var/lib/elasticsearch
#    environment:
#      - constraint:node==monitoring

  telegrafhost:
    image: 'mabsimms/telegraf-host:latest'
    deploy:
      mode: global
    environment:
      - INFLUX_SERVER=influxdb
      - INFLUX_PORT=8086
      - INFLUX_DB=host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  default:
    external:
      name: build2017-demo-network

volumes:
  grafana-data:

  influx-data:

