apiVersion: v1
data:
  INFLUX_DB: hosts
  INFLUX_PORT: "8086"
  INFLUX_SERVER: influxdb.default
  telegraf.conf: |
    # Global tags can be specified here in key="value" format.
    [global_tags]

    # Configuration for telegraf agent
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      flush_interval = "10s"
      flush_jitter = "1s"
      precision = ""

      ## Logging configuration:
      debug = false
      quiet = false
      logfile = ""

      ## Override default hostname, if empty use os.Hostname()
      hostname = ""
      omit_hostname = false

    # Configuration for influxdb server to send metrics to
    [[outputs.influxdb]]
      urls = ["http://$INFLUX_SERVER:$INFLUX_PORT"] # required
      database = "$INFLUX_DB"
      timeout = "5s"

    ###############################################################################
    # INPUT PLUGINS

    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false

    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs"]

    [[inputs.diskio]]

    [[inputs.kernel]]

    [[inputs.mem]]

    [[inputs.net]]

    [[inputs.processes]]

    [[inputs.swap]]

    [[inputs.system]]

    # # Read metrics about docker containers
    [[inputs.docker]]
       ## Docker Endpoint
       ##   To use TCP, set endpoint = "tcp://[ip]:[port]"
       ##   To use environment variables (ie, docker-machine), set endpoint = "ENV"
       endpoint = "unix:///var/run/docker.sock"

       ## Only collect metrics for these containers, collect all if empty
       container_names = []

       ## Timeout for docker list, info, and stats commands
       timeout = "5s"

       perdevice = true
       total = false
kind: ConfigMap
metadata:
  creationTimestamp: 2017-07-07T22:20:12Z
  name: telegraf-agent-config
  namespace: default
  resourceVersion: "87201"
  selfLink: /api/v1/namespaces/default/configmaps/telegraf-agent-config
  uid: 717ce154-6362-11e7-ab14-000d3a03b2f8
