apiVersion: v1
data:
  SQL_DATASOURCE: tcp:sqlserver,1433
kind: ConfigMap
metadata:
  creationTimestamp: 2017-07-09T19:10:19Z
  name: webapp-config
  namespace: default
  resourceVersion: "313702"
  selfLink: /api/v1/namespaces/default/configmaps/webapp-config
  uid: 3fc355e6-64da-11e7-ab14-000d3a03b2f8
